"""
Training Data Utilities and Entity-Level Validation Splitting.

Component: Lakshya (ML Matching Model)
Responsibilities:
- Constructing labeled candidate pairs from candidate generation & ground truth.
- Hard negative sampling strategies (similarity-weighted, top-k, hybrid).
- Entity-level train/validation splitting (strictly non-overlapping S1 entities).
- Memory optimization and batching helpers for multi-million row datasets.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Generator, Iterable, List, Optional, Set, Tuple, Union

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

logger = logging.getLogger(__name__)


# ==============================================================================
# 1. LABELED PAIRS CONSTRUCTION
# ==============================================================================

def construct_labeled_pairs(
    candidate_pairs: pd.DataFrame,
    ground_truth: Union[pd.DataFrame, Set[Tuple[Any, Any]]],
    s1_col: str = "s1_entity_id",
    candidate_col: str = "candidate_entity_id",
    label_col: str = "label",
) -> pd.DataFrame:
    """
    Construct labeled candidate pairs from candidate pairs and ground truth.
    
    Positive pair (label = 1):
        Candidate pair (s1_entity_id, candidate_entity_id) exists in ground truth.
    Negative pair (label = 0):
        Candidate pair was generated by candidate generation / blocking,
        but does NOT exist in ground truth.
        
    Note:
        Does NOT create arbitrary Cartesian-product negatives. The model
        trains strictly on realistic negatives produced by blocking.
        
    Args:
        candidate_pairs: DataFrame of generated candidate pairs (from Aditya's blocking).
        ground_truth: DataFrame with [s1_col, candidate_col] or set of (s1_id, candidate_id) tuples.
        s1_col: Column name for S1 entity identifier.
        candidate_col: Column name for candidate entity identifier.
        label_col: Name of the output binary label column (1 = match, 0 = non-match).
        
    Returns:
        DataFrame with an added binary column `label` (1 or 0).
    """
    if candidate_pairs.empty:
        df = candidate_pairs.copy()
        df[label_col] = pd.Series(dtype=np.int32)
        return df

    if s1_col not in candidate_pairs.columns or candidate_col not in candidate_pairs.columns:
        raise ValueError(
            f"candidate_pairs must contain columns '{s1_col}' and '{candidate_col}'."
        )

    # Remove potential duplicate candidate pairs
    df_pairs = candidate_pairs.drop_duplicates(subset=[s1_col, candidate_col]).copy()

    if isinstance(ground_truth, set):
        gt_set = ground_truth
    elif isinstance(ground_truth, pd.DataFrame):
        if s1_col not in ground_truth.columns or candidate_col not in ground_truth.columns:
            raise ValueError(
                f"ground_truth DataFrame must contain columns '{s1_col}' and '{candidate_col}'."
            )
        gt_set = set(zip(ground_truth[s1_col], ground_truth[candidate_col]))
    else:
        raise TypeError("ground_truth must be a pandas DataFrame or a set of (s1_id, candidate_id) tuples.")

    # Fast vectorized tuple lookup using MultiIndex / set membership
    is_positive = [
        (s1, cand) in gt_set
        for s1, cand in zip(df_pairs[s1_col], df_pairs[candidate_col])
    ]
    df_pairs[label_col] = np.array(is_positive, dtype=np.int32)

    n_pos = int(df_pairs[label_col].sum())
    n_neg = len(df_pairs) - n_pos
    logger.info(
        "Constructed labeled pairs: %d total (%d positives, %d negatives, ratio %.2f:1)",
        len(df_pairs),
        n_pos,
        n_neg,
        (n_neg / n_pos) if n_pos > 0 else 0.0,
    )
    return df_pairs


# ==============================================================================
# 2. CONFIGURABLE HARD-NEGATIVE SAMPLING
# ==============================================================================

def sample_negatives(
    labeled_pairs: pd.DataFrame,
    negative_to_positive_ratio: float = 5.0,
    hard_negative_strategy: str = "similarity_weighted",
    similarity_col: str = "name_fuzzy_similarity",
    random_state: int = 42,
    min_negatives_per_s1: int = 1,
    max_negatives_per_s1: Optional[int] = None,
    s1_col: str = "s1_entity_id",
    label_col: str = "label",
) -> pd.DataFrame:
    """
    Perform negative candidate sampling with hard-negative strategies.
    
    Strategies supported:
    - 'random': Uniform random sampling across negative candidate pairs.
    - 'similarity_weighted': Sample negatives with probability proportional to similarity score
                             (hard negatives like high name similarity / same country get sampled more).
    - 'top_k_per_s1': Sample the top-k highest similarity candidate negatives for each S1.
    - 'hard_first': Select top-N highest similarity negatives globally.
    - 'hybrid': Mix of 70% hard (similarity-weighted/top-k) and 30% uniform random negatives.
    
    Args:
        labeled_pairs: DataFrame of labeled pairs with label_col (1 for match, 0 for negative).
        negative_to_positive_ratio: Desired ratio of negatives:positives (e.g. 5.0 = 5 negatives per 1 positive).
        hard_negative_strategy: Strategy name ('similarity_weighted', 'top_k_per_s1', 'hard_first', 'random', 'hybrid').
        similarity_col: Feature column used for hard-negative ranking (e.g. 'name_fuzzy_similarity').
        random_state: Random seed for deterministic reproducibility.
        min_negatives_per_s1: Minimum negatives to retain per S1 if available.
        max_negatives_per_s1: Optional maximum negatives to retain per S1.
        s1_col: Column name for S1 entity identifier.
        label_col: Binary label column name.
        
    Returns:
        Balanced and sampled DataFrame containing all positive pairs and selected negatives.
    """
    if labeled_pairs.empty:
        return labeled_pairs.copy()

    positives = labeled_pairs[labeled_pairs[label_col] == 1].copy()
    negatives = labeled_pairs[labeled_pairs[label_col] == 0].copy()

    n_pos = len(positives)
    n_neg = len(negatives)

    if n_pos == 0:
        logger.warning("No positive pairs found in dataset. Returning all rows.")
        return labeled_pairs.copy()

    target_n_neg = int(round(n_pos * negative_to_positive_ratio))

    if n_neg <= target_n_neg:
        logger.info(
            "Available negatives (%d) <= target negatives (%d). Keeping all negatives.",
            n_neg,
            target_n_neg,
        )
        return labeled_pairs.copy()

    rng = np.random.default_rng(random_state)

    # Resolve similarity scores for hard-negative weighting
    sim_scores = None
    if similarity_col in negatives.columns:
        sim_scores = negatives[similarity_col].fillna(0.0).values.astype(np.float64)
        # Ensure non-negative scores
        sim_scores = np.clip(sim_scores, 0.0, 1.0)
    else:
        logger.warning(
            "similarity_col '%s' not found in negatives. Falling back to 'random' strategy.",
            similarity_col,
        )
        hard_negative_strategy = "random"

    if hard_negative_strategy == "random":
        chosen_neg_indices = rng.choice(negatives.index, size=target_n_neg, replace=False)
        sampled_negatives = negatives.loc[chosen_neg_indices]

    elif hard_negative_strategy == "similarity_weighted":
        assert sim_scores is not None
        # Add small smoothing epsilon so even low-similarity pairs have non-zero probability
        weights = sim_scores + 0.01
        probs = weights / np.sum(weights)
        chosen_neg_indices = rng.choice(negatives.index, size=target_n_neg, replace=False, p=probs)
        sampled_negatives = negatives.loc[chosen_neg_indices]

    elif hard_negative_strategy == "hard_first":
        assert sim_scores is not None
        sorted_indices = negatives.index[np.argsort(-sim_scores)[:target_n_neg]]
        sampled_negatives = negatives.loc[sorted_indices]

    elif hard_negative_strategy == "top_k_per_s1":
        # Group by S1 and take top-k candidates per S1
        # Calculate k needed per S1
        unique_s1s = negatives[s1_col].nunique()
        k = max(1, int(np.ceil(target_n_neg / unique_s1s))) if unique_s1s > 0 else 1
        if max_negatives_per_s1 is not None:
            k = min(k, max_negatives_per_s1)
        k = max(k, min_negatives_per_s1)

        grouped = negatives.sort_values(by=similarity_col, ascending=False).groupby(s1_col, group_keys=False)
        top_k_negatives = grouped.head(k)

        if len(top_k_negatives) > target_n_neg:
            chosen_indices = rng.choice(top_k_negatives.index, size=target_n_neg, replace=False)
            sampled_negatives = top_k_negatives.loc[chosen_indices]
        else:
            sampled_negatives = top_k_negatives

    elif hard_negative_strategy == "hybrid":
        # 70% similarity weighted hard negatives + 30% uniform random exploration
        n_hard = int(round(target_n_neg * 0.70))
        n_rand = target_n_neg - n_hard

        assert sim_scores is not None
        weights = sim_scores + 0.01
        probs = weights / np.sum(weights)
        hard_indices = rng.choice(negatives.index, size=n_hard, replace=False, p=probs)

        remaining_indices = list(set(negatives.index) - set(hard_indices))
        if len(remaining_indices) >= n_rand:
            rand_indices = rng.choice(remaining_indices, size=n_rand, replace=False)
        else:
            rand_indices = remaining_indices

        chosen_indices = np.concatenate([hard_indices, rand_indices])
        sampled_negatives = negatives.loc[chosen_indices]

    else:
        raise ValueError(
            f"Unknown hard_negative_strategy '{hard_negative_strategy}'. "
            f"Expected one of: ['random', 'similarity_weighted', 'hard_first', 'top_k_per_s1', 'hybrid']"
        )

    # Combine positives and sampled negatives
    result_df = pd.concat([positives, sampled_negatives], ignore_index=True)
    # Shuffle for training
    result_df = result_df.sample(frac=1.0, random_state=random_state).reset_index(drop=True)

    logger.info(
        "Sampled negatives (%s): %d positives + %d negatives = %d total pairs (ratio %.2f:1)",
        hard_negative_strategy,
        len(positives),
        len(sampled_negatives),
        len(result_df),
        (len(sampled_negatives) / len(positives)) if len(positives) > 0 else 0.0,
    )
    return result_df


# ==============================================================================
# 3. ENTITY-LEVEL VALIDATION SPLITTING
# ==============================================================================

def create_entity_split(
    data_or_ids: Union[pd.DataFrame, pd.Series, Iterable[Any]],
    test_size: float = 0.2,
    random_state: int = 42,
    s1_col: str = "s1_entity_id",
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Split entities strictly at the S1 entity level.
    
    Guarantees that no S1 entity occurs in both the training and validation sets.
    This prevents data leakage and mimics real inference on unseen query entities.
    
    Args:
        data_or_ids: DataFrame containing s1_col, or a Series / iterable of unique S1 entity IDs.
        test_size: Proportion of S1 entities to allocate to validation (default: 0.2).
        random_state: Random seed for deterministic reproducibility.
        s1_col: Column name containing S1 entity IDs if DataFrame is passed.
        
    Returns:
        (train_s1_ids, val_s1_ids) as two 1D numpy arrays of entity IDs.
    """
    if isinstance(data_or_ids, pd.DataFrame):
        if s1_col not in data_or_ids.columns:
            raise ValueError(f"DataFrame must contain s1 entity column '{s1_col}'.")
        unique_s1_ids = data_or_ids[s1_col].unique()
    elif isinstance(data_or_ids, pd.Series):
        unique_s1_ids = data_or_ids.unique()
    else:
        unique_s1_ids = np.unique(list(data_or_ids))

    if len(unique_s1_ids) == 0:
        return np.array([], dtype=object), np.array([], dtype=object)

    if len(unique_s1_ids) == 1:
        # Edge case: single entity
        return unique_s1_ids, np.array([], dtype=object)

    train_s1_ids, val_s1_ids = train_test_split(
        unique_s1_ids,
        test_size=test_size,
        random_state=random_state,
        shuffle=True,
    )

    # Verification of zero entity overlap
    overlap = set(train_s1_ids).intersection(set(val_s1_ids))
    assert len(overlap) == 0, f"Entity leakage detected! Overlap: {len(overlap)} S1 IDs."

    logger.info(
        "Entity split created: %d train S1s, %d val S1s (val ratio %.2f, 0 overlap)",
        len(train_s1_ids),
        len(val_s1_ids),
        len(val_s1_ids) / len(unique_s1_ids),
    )
    return train_s1_ids, val_s1_ids


def split_pairs_by_entity(
    pairs_df: pd.DataFrame,
    train_s1_ids: Union[Iterable[Any], Set[Any]],
    val_s1_ids: Union[Iterable[Any], Set[Any]],
    s1_col: str = "s1_entity_id",
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Partition candidate pairs DataFrame into train and validation DataFrames
    given disjoint S1 entity ID sets.
    
    Args:
        pairs_df: DataFrame of candidate pairs.
        train_s1_ids: Iterable/set of S1 IDs allocated to training.
        val_s1_ids: Iterable/set of S1 IDs allocated to validation.
        s1_col: S1 entity ID column name.
        
    Returns:
        (train_pairs_df, val_pairs_df)
    """
    train_set = set(train_s1_ids)
    val_set = set(val_s1_ids)

    train_mask = pairs_df[s1_col].isin(train_set)
    val_mask = pairs_df[s1_col].isin(val_set)

    train_df = pairs_df[train_mask].reset_index(drop=True)
    val_df = pairs_df[val_mask].reset_index(drop=True)

    return train_df, val_df


# ==============================================================================
# 4. MEMORY OPTIMIZATION & BATCH PROCESSING
# ==============================================================================

def optimize_memory_usage(df: pd.DataFrame, verbose: bool = False) -> pd.DataFrame:
    """
    Downcast numeric data types in DataFrame to reduce memory footprint by 50-75%.
    
    Useful for running multi-million pair datasets in Google Colab memory limits.
    
    Args:
        df: Input pandas DataFrame.
        verbose: If True, log memory reduction statistics.
        
    Returns:
        DataFrame with optimized data types.
    """
    start_mem = df.memory_usage().sum() / 1024**2 if not df.empty else 0.0

    for col in df.columns:
        col_type = df[col].dtype

        if pd.api.types.is_integer_dtype(col_type):
            c_min = df[col].min()
            c_max = df[col].max()
            if c_min >= 0:
                if c_max < 255:
                    df[col] = df[col].astype(np.uint8)
                elif c_max < 65535:
                    df[col] = df[col].astype(np.uint16)
                elif c_max < 4294967295:
                    df[col] = df[col].astype(np.uint32)
            else:
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)

        elif pd.api.types.is_float_dtype(col_type):
            df[col] = df[col].astype(np.float32)

    end_mem = df.memory_usage().sum() / 1024**2 if not df.empty else 0.0
    if verbose:
        logger.info(
            "Memory usage decreased from %.2f MB to %.2f MB (%.1f%% reduction)",
            start_mem,
            end_mem,
            100 * (start_mem - end_mem) / start_mem if start_mem > 0 else 0,
        )
    return df


def create_batches(
    df: pd.DataFrame,
    batch_size: int = 100000,
) -> Generator[pd.DataFrame, None, None]:
    """
    Yield slices of DataFrame in chunks for memory-efficient batch processing.
    
    Args:
        df: Input DataFrame.
        batch_size: Number of rows per batch.
        
    Yields:
        DataFrame chunks of size at most batch_size.
    """
    n_rows = len(df)
    for start_idx in range(0, n_rows, batch_size):
        yield df.iloc[start_idx : min(start_idx + batch_size, n_rows)]
